backend/api/admin/views.py
from flask import (
    Blueprint,
    abort,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import current_user, login_required

from app import db
from app.admin.forms import (
    ChangeAccountTypeForm,
    ChangeUserEmailForm,
    NewUserForm,
)
from app.decorators import admin_required
from app.email import send_email
from app.models import EditableHTML, Role, User

admin = Blueprint('admin', __name__)


@admin.route('/')
@login_required
@admin_required
def index():
    """Admin dashboard page."""
    return render_template('admin/index.html')


@admin.route('/new-user', methods=['GET', 'POST'])
@login_required
@admin_required
def new_user():
    """Create a new user."""
    form = NewUserForm()
    if form.validate_on_submit():
        user = User(
            role=form.role.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            email=form.email.data,
            password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('User {} successfully created'.format(user.full_name()),
              'form-success')
    return render_template('admin/new_user.html', form=form)


@admin.route('/users')
@login_required
@admin_required
def registered_users():
    """View all registered users."""
    users = User.query.all()
    roles = Role.query.all()
    return render_template(
        'admin/registered_users.html', users=users, roles=roles)


@admin.route('/user/<int:user_id>')
@admin.route('/user/<int:user_id>/info')
@login_required
@admin_required
def user_info(user_id):
    """View a user's profile."""
    user = User.query.filter_by(id=user_id).first()
    if user is None:
        abort(404)
    return render_template('admin/manage_user.html', user=user)


@admin.route('/user/<int:user_id>/change-email', methods=['GET', 'POST'])
@login_required
@admin_required
def change_user_email(user_id):
    """Change a user's email."""
    user = User.query.filter_by(id=user_id).first()
    if user is None:
        abort(404)
    form = ChangeUserEmailForm()
    if form.validate_on_submit():
        user.email = form.email.data
        db.session.add(user)
        db.session.commit()
        flash('Email for user {} successfully changed to {}.'.format(
            user.full_name(), user.email), 'form-success')
    return render_template('admin/manage_user.html', user=user, form=form)


@admin.route(
    '/user/<int:user_id>/change-account-type', methods=['GET', 'POST'])
@login_required
@admin_required
def change_account_type(user_id):
    """Change a user's account type."""
    if current_user.id == user_id:
        flash('You cannot change the type of your own account. Please ask '
              'another administrator to do this.', 'error')
        return redirect(url_for('admin.user_info', user_id=user_id))

    user = User.query.get(user_id)
    if user is None:
        abort(404)
    form = ChangeAccountTypeForm()
    if form.validate_on_submit():
        user.role = form.role.data
        db.session.add(user)
        db.session.commit()
        flash('Role for user {} successfully changed to {}.'.format(
            user.full_name(), user.role.name), 'form-success')
    return render_template('admin/manage_user.html', user=user, form=form)


@admin.route('/user/<int:user_id>/delete')
@login_required
@admin_required
def delete_user_request(user_id):
    """Request deletion of a user's account."""
    user = User.query.filter_by(id=user_id).first()
    if user is None:
        abort(404)
    return render_template('admin/manage_user.html', user=user)


@admin.route('/user/<int:user_id>/_delete')
@login_required
@admin_required
def delete_user(user_id):
    """Delete a user's account."""
    if current_user.id == user_id:
        flash('You cannot delete your own account. Please ask another '
              'administrator to do this.', 'error')
    else:
        user = User.query.filter_by(id=user_id).first()
        db.session.delete(user)
        db.session.commit()
        flash('Successfully deleted user %s.' % user.full_name(), 'success')
    return redirect(url_for('admin.registered_users'))


@admin.route('/_update_editor_contents', methods=['POST'])
@login_required
@admin_required
def update_editor_contents():
    """Update the contents of an editor."""

    edit_data = request.form.get('edit_data')
    editor_name = request.form.get('editor_name')

    editor_contents = EditableHTML.query.filter_by(
        editor_name=editor_name).first()
    if editor_contents is None:
        editor_contents = EditableHTML(editor_name=editor_name)
    editor_contents.value = edit_data

    db.session.add(editor_contents)
    db.session.commit()

    return 'OK', 200

backend/api/apps/views.py
from .. import db
from ..models.containers import (
    Template,
    TemplateItem,
    TemplateVariables
)
from ..models.container_schemes import (
    TemplateItemSchema,
    DeploySchema
)

from flask import Blueprint
from flask import (
    abort,
    jsonify,
    make_response,
    request,
    Response
)
from flask_jwt_extended import (
    jwt_required,
    jwt_optional
)
import json  # Used for getting template data
from json import JSONEncoder
from webargs import fields, validate
from sqlalchemy.exc import IntegrityError
from datetime import datetime
from webargs.flaskparser import use_args, use_kwargs
from werkzeug.exceptions import MethodNotAllowed, UnprocessableEntity

import os  # used for getting file type and deleting files
from urllib.parse import urlparse  # used for getting filetype from url
import urllib.request
import docker

apps = Blueprint('apps', __name__)

### Main List of Apps ###
@apps.route('/')
@jwt_required

def index():
    apps_list = []
    dclient = docker.from_env()
    apps = dclient.containers.list(all=True)
    for app in apps:
        attrs=app.attrs
        attrs.update(conv2dict('name', app.name))
        attrs.update(conv2dict('ports', app.ports))
        attrs.update(conv2dict('short_id', app.short_id))
        apps_list.append(attrs)
    data = apps_list
    return jsonify({ 'data': data })

def conv2dict(name, value):
    _tmp_attr = { name: value}
    return _tmp_attr

@apps.route('/<int:id>')
@jwt_required

def list_apps(id):
    try:
        template_item = TemplateItem.query.get_or_404(id)
        template_item_schema = TemplateItemSchema()
        data = template_item_schema.dump(template_item)
        return jsonify({ 'data': data })
    except IntegrityError as err:
        abort(400)

### Deploy App ###
@apps.route('/<int:id>/deploy', methods=['POST'])
@jwt_required

@use_args(DeploySchema(), location='json')
def deploy(args, id):
    '''curl -H "Content-Type: application/json" -X POST \
    -d '{"title":"Untitled", "image":"my:image", "ports":[{"proto": "tcp", "hport":2020}]}' \
    http://127.0.0.1:5000/api/apps/1/deploy
    '''
    print(args, id)
    try:
        launch = launch_app(
        args.get('name'),
        args.get('image'),
        conv_restart2data(args.get('restart_policy')),
        conv_ports2data(args.get('ports')),
        conv_volumes2data(args.get('volumes')),
        conv_env2data(args.get('env')),
        conv_sysctls2data(args.get('sysctls')),
        conv_caps2data(args.get('cap_add')))

        launch_logs = launch.logs()
        decoded_logs = launch_logs.decode("utf-8")

        data = jsonify({ 'logs': decoded_logs})
    except Exception as exc: raise
    print('done deploying')
    # print(id, title, image)
    # print(args, kwargs)
    return data, 200

# Input Format:
# [
#     {
#         'cport': '53',
#         'hport': '53',
#         'proto': 'tcp',
#     },
#     ...
# ]
# Result Format:
# {
#     '53/tcp': ('0.0.0.0', 53),
#     '53/udp': ('0.0.0.0', 53),
#     '67/udp': ('0.0.0.0', 67),
#     '80/tcp': ('0.0.0.0', 1010),
#     '443/tcp': ('0.0.0.0', 4443)
# }
def conv_ports2data(data):
    ports = {}
    for d in data:
        cport = d.get('cport')
        hport = d.get('hport')
        proto = d.get('proto')
        if not hport: hport = None
        ports.update({str(cport)+'/'+proto:hport for d in data})
    return ports

# Input Format:
# [
#     {
#         'container': '/mnt/vol2',
#         'bind': '/home/user1'
#     }
#     ...
# ]
# Result Format:
# {
#     '/home/user1/': {'bind': '/mnt/vol2', 'mode': 'rw'},
#     '/var/www': {'bind': '/mnt/vol1', 'mode': 'ro'}
# }
def conv_volumes2data(data):
    t_variables = TemplateVariables.query.all()
    for volume in data:
        if volume['bind']:
            for t_var in t_variables:
                if t_var.variable in volume['bind']:
                  new_path = volume['bind'].replace(t_var.variable, t_var.replacement)
                  volume['bind'] = new_path
    volume_data = dict((d['bind'], {'bind': d['container'], 'mode': 'rw'}) for d in data)

    return volume_data

# Input Format:
# [
#     {
#         'name': 'SOMEVARIABLE',
#         'default': '1000'
#     }
#     ...
# ]
# Result Format:
# [
#     "SOMEVARIABLE=xxx", "OTHERVARIABLE=yyy"
# ]
def conv_env2data(data):
    # Set is depracated. Name is the actual value. Label is the name of the field.
    # Label is the label of the label field.
    delim = '='
    return [delim.join((d['name'], d['default'])) for d in data]

def conv_sysctls2data(data):
    if data:
        return dict((d['name'], d['value']) for d in data)
    else:
        sysctls = None
        return sysctls
def conv_caps2data(data):
    if data:
        return data
    else:
        caps = None
        return caps
def conv_restart2data(data):
    if data:
        return {'name': data}
    else:
        restart = None
        return restart

def launch_app(name, image, restart_policy, ports, volumes, env, sysctls, caps):
    dclient = docker.from_env()
    lauch = dclient.containers.run(
        name=name,
        image=image,
        restart_policy=restart_policy,
        ports=ports,
        volumes=volumes,
        environment=env,
        sysctls=sysctls,
        cap_add=caps,
        detach=True
    )
    print(lauch)
    print(f'''Container started successfully.
       Name: {name},
      Image: {image},
      Ports: {ports},
    Volumes: {volumes},
        Env: {env}''')
    return lauch

### Docker Actions ###
@apps.route('/<container_name>/<action>')
@jwt_required

def app_actions(container_name, action):
    err = None
    apps_list = []
    dclient = docker.from_env()
    container = dclient.containers.get(container_name)
    # _action = action + '()'
    _action = getattr(container, action)
    if action == 'remove':
        try:
          _action(force=True)
        except Exception as exc:
            err = f"{exc}"
    else:
        try: 
          _action()
        except Exception as exc:
            err = exc.explanation
    
    apps = dclient.containers.list(all=True)
    for app in apps:
        attrs=app.attrs
        attrs.update(conv2dict('name', app.name))
        attrs.update(conv2dict('ports', app.ports))
        attrs.update(conv2dict('short_id', app.short_id))
        apps_list.append(attrs)
    data = apps_list
    return jsonify({ 'data': data, 'error': err })

def conv2dict(name, value):
    _tmp_attr = { name: value}
    return _tmp_attr

### Container Details ###
@apps.route('/<container_name>')
@jwt_required

def app_details(container_name):
    dclient = docker.from_env()
    container = dclient.containers.get(container_name)
    attrs = container.attrs

    #Add extra values to Attrs
    attrs.update(conv2dict('ports', container.ports))
    attrs.update(conv2dict('short_id', container.short_id))
    attrs.update(conv2dict('name', container.name))


    data=attrs
    print(jsonify({ 'data': data }))
    return jsonify({ 'data': data })

# Convert fields we need into a value we can add to attrs Format: conv2dict('name', container.value)
def conv2dict(name, value):
    _tmp_attr = { name: value}
    return _tmp_attr

### Container Processes ###
@apps.route('/<container_name>/processes')
@jwt_required

def app_processes(container_name):
    dclient = docker.from_env()
    container = dclient.containers.get(container_name)
    if container.status == 'running':
        processes = container.top()
        data = processes
    else:
        print('Container ' + container.name + ' is not running')
        data = None
    print(jsonify({ 'data': data }))
    return jsonify({ 'data': data })

### Container Logs ###
@apps.route('/<container_name>/logs')
@jwt_required
def logs(container_name):
    dclient = docker.from_env()
    container = dclient.containers.get(container_name)
    if container.status == 'running':
        logs = []
        raw_logs = container.logs()
        decoded_logs = raw_logs.decode("utf-8")
        data = jsonify({ 'logs': decoded_logs})
        print(data)
    else:
        print('Container ' + container.name + ' is not running')
        return jsonify({'msg': 'Container not running'}), 404
    return data, 200

app/templates/apps/add_app.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="ui stackable grid container">
        <div class="fourteen wide tablet twelve wide computer centered column">
            <div class="ui compact basic buttons">
                <a class="ui basic compact button" href="{{ url_for('apps.index') }}">
                    <i class="caret left icon"></i>
                    Back to dashboard
                </a>
            </div>
            <h2 class="ui header">
                New Application
                <div class="sub header">
                    Select the template you would like to use.
                </div>
            </h2>

            <div class="ui menu">
                <div id="select-role" class="ui dropdown item">
                    <div class="text">
                        All Categories
                    </div>
                    <i class="dropdown icon"></i>
                    <div class="menu">
                        <div class="item" data-value="">All Categories</div>
                        {% for a in apps %}
                            <div class="item" data-value="{{ a.categories }}">{{ a.categories }}</div>
                        {% endfor %}
                    </div>
                </div>
                <div class="ui right search item">
                    <div class="ui transparent icon input">
                        <input id="search-users" type="text" placeholder="Search users…">
                        <i class="search icon"></i>
                    </div>
                </div>
            </div>

            {# Use overflow-x: scroll so that mobile views don't freak out
             # when the table is too wide #}
            <div style="overflow-x: scroll;">
                <table class="ui searchable sortable unstackable selectable very basic table">
                    <thead>
                        <tr>
                            <th class="sorted ascending">Title</th>
                            <th>Desctiption</th>
                            <th>Catagory</th>
                            <th>Platform</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for a in apps | sort(attribute='title') %} {# Generates table with list of applications in add apps section#}
                        <tr onclick="window.location.href = '{{ url_for('apps.deploy_app', app_id=a.id,) }}';">
                            <td><a class = "ui large label"><img class ="ui right spaced image" src={{ a.logo|tojson }}>{{ a.title }}</td>
                            <td>{{ a.description }}</td>
                            <td>
                            {%- for categories in a.categories %}
                                <a class = "ui label">{{ categories }}</a>
                            {%- endfor%}
                            </td>
                            <td>{{ a.platform }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#search-users').keyup(function () {
                var searchText = $(this).val();
                if (searchText.length > 0) {
                    $('tbody td:icontains(' + searchText + ')').addClass('positive');
                    $('td.positive').not(':icontains(' + searchText + ')').removeClass('positive');
                    $('tbody td').not(':icontains(' + searchText + ')').closest('tr').addClass('hidden').hide();
                    $('tr.hidden:icontains(' + searchText + ')').removeClass('hidden').show();
                } else {
                    $('td.positive').removeClass('positive');
                    $('tr.hidden').removeClass('hidden').show();
                }
            });

            $('#select-role').dropdown({
                onChange: function (value, text, $selectedItem) {
                    $('app.categories:contains(' + value + ')').closest('tr').removeClass('hidden').show();
                    $('app.categories').not(':contains(' + value + ')').closest('tr').addClass('hidden').hide();
                }
            });
        });
    </script>
{% endblock %}

app/templates/apps/index.html
{% extends 'layouts/base.html' %}

{% macro dashboard_option(title, endpoint, description=None, icon=None) %}
    <a class="column" href="{{ url_for(endpoint) }}">
        <div class="ui padded segment">
            <h3 class="ui header">
                {% if icon is not none %}
                    <i class="{{ icon }}"></i>
                {% endif %}
                <div class="content">
                    {{ title }}
                    {% if description is not none %}
                        <div class="sub header">
                            {{ description }}
                        </div>
                    {% endif %}
                </div>
            </h3>
        </div>
    </a>
{% endmacro %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <!-- Flash messages if they exist -->
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            <ul>
                {% for message in messages %}
                <li style="color: tomato;">{{ message }}</li>
                {% endfor %}
            </ul>
            <hr>
            {% endif %}
            {% endwith %}

            <h2 class="ui header">
                App Dashboard
            </h2>
            <div class="ui two column stackable grid"> {# Code for deploying the main apps dashboard #}
                {{ dashboard_option('View Apps', 'apps.running_apps',
                                    description='View and manage running apps', icon='list layout icon') }}
                {{ dashboard_option('Add New Apps', 'apps.view_apps',
                                    description='Launch a new application.', icon='plus icon') }}
            </div>
        </div>
    </div>
{% endblock %}

app/templates/apps/manage_template.html
% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}

{% set deletion_endpoint = 'admin.delete_user_request' %}

{% set endpoints = [
    ('admin.user_info', 'User information'),
    ('admin.change_user_email', 'Change email address'),
    ('admin.change_account_type', 'Change account type'),
    (deletion_endpoint, 'Delete user')
] %}

{% macro navigation(items) %}
    <div class="ui vertical fluid secondary menu">
        {% for route, name in items %}
            {% set href = url_for(route, user_id=user.id) %}
            <a class="item {% if request.endpoint == route %}active{% endif %}" href="{{ href }}">
                {{ name }}
            </a>
        {% endfor %}
    </div>
{% endmacro %}

{% macro user_info(user) %}
    <table class="ui compact definition table">
        <tr><td>Full name</td><td>{{ '%s %s' % (user.first_name, user.last_name) }}</td></tr>
        <tr><td>Email address</td><td>{{ user.email }}</td></tr>
        <tr><td>Account type</td><td>{{ user.role.name }}</td></tr>
    </table>
{% endmacro %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <a class="ui basic compact button" href="{{ url_for('admin.registered_users') }}">
                <i class="caret left icon"></i>
                Back to all users
            </a>
            <h2 class="ui header">
                {{ user.full_name() }}
                <div class="sub header">View and manage {{ user.first_name }}’s account.</div>
            </h2>
        </div>
        <div class="stretched divided very relaxed row">
            <div class="four wide column">
                {{ navigation(endpoints) }}
            </div>
            <div class="eight wide column">
                {% if request.endpoint == deletion_endpoint %}
                    <h3 class="ui red block header">
                        <i class="warning circle icon"></i>
                        <div class="content">
                            This action is permanent
                            <div class="sub header">
                                Deleting a user account is not a reversible change. Any information associated
                                with this account will be removed, and cannot be recovered.
                            </div>
                        </div>
                    </h3>

                    <div class="ui form">
                        <div class="inline field">
                            <div class="ui deletion checkbox">
                                <input type="checkbox" tabindex="0" class="hidden">
                                <label>I understand that this action cannot be undone.</label>
                            </div>
                        </div>
                        <a class="ui disabled negative deletion button">
                            Delete this user
                        </a>
                    </div>
                    </div>
                {% elif form %}
                    {{ f.render_form(form) }}
                {% else %}
                    {{ user_info(user) }}
                {% endif %}
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $('.deletion.checkbox').checkbox({
            onChecked: function() {
                $('.deletion.button').removeClass('disabled')
                        .attr('href', '{{ url_for('admin.delete_user', user_id=user.id) }}');
            },
            onUnchecked: function() {
                $('.deletion.button').addClass('disabled').removeAttr('href');
            }
        });
    </script>
{% endblock %}

app/templates/apps/new_compose.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% import 'macros/check_password.html' as check %}

{% block scripts %}
{% endblock %}
{# Not in use yet #}
{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <a class="ui basic compact button" href="{{ url_for('apps.index') }}">
                <i class="caret left icon"></i>
                Back to dashboard
            </a>
            <h2 class="ui header">
                New Compose Template
                <div class="sub header">Add a new app template</div>
                {% set flashes = {
                    'error':   get_flashed_messages(category_filter=['form-error']),
                    'warning': get_flashed_messages(category_filter=['form-check-email']),
                    'info':    get_flashed_messages(category_filter=['form-info']),
                    'success': get_flashed_messages(category_filter=['form-success'])
                } %}
    
                {{ f.begin_form(form, flashes) }}

                    {{ f.render_form_field(form.template_name)}}
                    {{ f.render_form_field(form.template_url) }}
                    {{ f.render_form_field(form.description)}}
                    {{ f.render_form_field(form.submit) }}
    
                {{ f.end_form() }}
            </h2>
        </div>
    </div>
{% endblock %}

app/templates/apps/new_template.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% import 'macros/check_password.html' as check %}

{% block scripts %}
{% endblock %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <a class="ui basic compact button" href="{{ url_for('apps.index') }}">
                <i class="caret left icon"></i>
                Back to dashboard
            </a>
            <h2 class="ui header">
                New App Template
                <div class="sub header">Add a new app template</div>
                {% set flashes = {
                    'error':   get_flashed_messages(category_filter=['form-error']),
                    'warning': get_flashed_messages(category_filter=['form-check-email']),
                    'info':    get_flashed_messages(category_filter=['form-info']),
                    'success': get_flashed_messages(category_filter=['form-success'])
                } %}
                    {# Form for adding a new template #}
                {{ f.begin_form(form, flashes) }}

                    {{ f.render_form_field(form.template_name)}}
                    {{ f.render_form_field(form.template_url) }}
                    {{ f.render_form_field(form.submit) }}
    
                {{ f.end_form() }}
            </h2>
        </div>
    </div>
{% endblock %}

app/templates/apps/view_apps.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="ui stackable grid container">
        <div class="fourteen wide tablet twelve wide computer centered column">
            <div class="ui compact basic buttons">
                <a class="ui basic compact button" href="{{ url_for('apps.index') }}">
                    <i class="caret left icon"></i>
                    Back to dashboard
                </a>
            </div>
            <h2 class="ui header">
                Apps
                <div class="sub header">
                    View and manage currently running Apps.
                </div>
            </h2>

            <div class="ui menu">
                <div class="ui right search item">
                    <div class="ui transparent icon input">
                        <input id="search-users" type="text" placeholder="Search apps…">
                        <i class="search icon"></i>
                    </div>
                </div>
            </div>

            {# Use overflow-x: scroll so that mobile views don't freak out
             # when the table is too wide #}
            <div style="overflow-x: auto;">
                <table class="ui collapsing searchable sortable two column unstackable selectable very basic table">
                    <thead>
                        <tr>
                            <th class="sorted ascending">App Name</th>
                            <th>App Ports</th>
                            <th>Mount Points</th>
                            <th>App Status</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for a in apps | sort(attribute='name') %} {# Show table of templates #}
                        <tr onclick="window.location.href = '{{ url_for('apps.container_info', container_name=a.name) }}';">
                            <td class="two wide">{{ a.name }}</td>
                            <td class="two wide">
                            {% for port in a.ports.values() %}
                                {% if port %}
                                    {% for entry in port %}
                                        {{entry.get('HostIp')}}:{{entry.get('HostPort')}}
                                    {% endfor %}
                                {% endif %}
                            {% endfor %}
                            </td>
                            <td>
                            {% for mount in a.attrs.Mounts %}
                                {% if mount %}
                                    {{ mount.get('Destination') }}:{{ mount.get('Source') }},<br>
                                {% endif %}
                            {% endfor %}
                            </td>
                            <td>{{ a.status }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#search-users').keyup(function () {
                var searchText = $(this).val();
                if (searchText.length > 0) {
                    $('tbody td:icontains(' + searchText + ')').addClass('positive');
                    $('td.positive').not(':icontains(' + searchText + ')').removeClass('positive');
                    $('tbody td').not(':icontains(' + searchText + ')').closest('tr').addClass('hidden').hide();
                    $('tr.hidden:icontains(' + searchText + ')').removeClass('hidden').show();
                } else {
                    $('td.positive').removeClass('positive');
                    $('tr.hidden').removeClass('hidden').show();
                }
            });

            $('#select-role').dropdown({
                onChange: function (value, text, $selectedItem) {
                    $('td.user.role:contains(' + value + ')').closest('tr').removeClass('hidden').show();
                    $('td.user.role').not(':contains(' + value + ')').closest('tr').addClass('hidden').hide();
                }
            });
        });
    </script>
{% endblock %}