app/app_templates/__init__.py
from app.app_templates.views import templates  # noqa

app/app_templates/views.py
from flask import (
    Blueprint,
    abort,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import current_user, login_required

from app import db
from app.app_templates.forms import (
    TemplateForm,
    ComposeForm,
)
from app.decorators import admin_required
from app.email import send_email
from app.models import Template, TemplateContent, Compose

import wget
import os  # used for getting file type and deleting files
from urllib.parse import urlparse  # used for getting filetype from url
import urllib.request
import json  # Used for getting template data
import docker


# used to reset the object for later use within the db.session
from sqlalchemy.orm.session import make_transient
from datetime import datetime


templates = Blueprint('templates', __name__)


@templates.route('/')
@login_required
@admin_required
def index():
    """Apps dashboard page."""
    return render_template('app_templates/index.html')


@templates.route('/view')
@login_required
@admin_required
def view_templates():
    """ View all templates """
    template = Template.query.all()
    return render_template('app_templates/view_templates.html', template=template)


@templates.route('/templates/<int:template_id>')
@templates.route('/templates/<int:template_id>/info')
@login_required
@admin_required
def template_info(template_id):
    """ View template info. """
    template = Template.query.get_or_404(template_id)
    return render_template('app_templates/manage_templates.html', template=template)


@templates.route('/templates/<int:template_id>/content', methods=['GET', 'POST'])
@login_required
@admin_required
def template_content(template_id):
    """ Generate a list of apps associated with the template based on id """
    template = Template.query.get_or_404(template_id)
    apps = TemplateContent.query.join(
        Template, Template.id == TemplateContent.template_id
    ).with_entities(
        TemplateContent.title,
        TemplateContent.logo,
        TemplateContent.description,
        TemplateContent.categories,
        TemplateContent.id
    ).filter(
        TemplateContent.template_id==template_id
    ).order_by(
        TemplateContent.title.asc()
    ).all()
    return render_template('app_templates/manage_templates.html', **locals())

@templates.route('/templates/<int:template_id>/content/<int:app_id>')
@login_required
@admin_required
def template_content_app(template_id, app_id):
    template = Template.query.get_or_404(template_id)
    app = TemplateContent.query.get_or_404(app_id)
    return render_template('app_templates/app_info.html', **locals())



# combine those two using methods GET and POST
@templates.route('/apps/<int:template_id>/delete')
@login_required
@admin_required
def delete_template_request(template_id):
    """Request deletion of a template."""
    template = Template.query.get_or_404(template_id)
    return render_template('app_templates/manage_templates.html', template=template)

# combine those two using methods GET and POST
@templates.route('/apps/<int:template_id>/_delete')
@login_required
@admin_required
def delete_template(template_id):
    """Delete a template."""
    template = Template.query.get_or_404(template_id)
    db.session.delete(template)
    db.session.commit()
    flash('Successfully deleted template.')
    return redirect(url_for('templates.view_templates'))


@templates.route('/new-template', methods=['GET', 'POST'])  # Set URL
@login_required
@admin_required
def new_template():
    """Add a new app template."""
    # Set the form for this page
    form = TemplateForm(request.form)
    if form.validate_on_submit():
        # Check the file type and depending on the file, download it and add it
        # to the db.
        template_name = form.template_name.data
        template_url = form.template_url.data
        template = Template(
            name=template_name,
            url=template_url,
        )
        # Break down template into individual apps and then put their data into
        # the db for later use.
        try:
            # Opens the JSON and iterate over the content.
            with urllib.request.urlopen(template_url) as file:
                for entry in json.load(file):

                    ports = conv_ports2dict(entry.get('ports', []))

                    # Optional use classmethod from_dict
                    template_content = TemplateContent(
                        type=int(entry['type']),
                        title=entry['title'],
                        platform=entry['platform'],
                        description=entry.get('description', ''),
                        name=entry.get('name', entry['title'].lower()),
                        logo=entry.get('logo', ''),
                        image=entry.get('image', ''),
                        notes=entry.get('note', ''),
                        categories=entry.get('categories', ''), # default: '' or []
                        restart_policy=entry.get('restart_policy'),
                        sysctls=entry.get('sysctls'),
                        ports=ports,
                        volumes=entry.get('volumes'),
                        env=entry.get('env'),
                    )
                    template.items.append(template_content)
        except (OSError, TypeError, ValueError) as err:
            # Optional handle KeyError here too.
            print('data request failed', err)
            raise

        try:
            db.session.add(template)
            db.session.commit()
        except SQLAlchemyError as err:
            print('database transaction failed')
            db.session.rollback()
            raise

        return redirect(url_for('templates.index'))
    return render_template('app_templates/new_template.html', form=form)


# begin utils.py
# Note: I use a different folder structure in my project.

import re

REGEXP_PORT_ASSIGN = r'^(?:\d{1,5}\:)?\d{1,5}|\:\d{1,5}/(?:tcp|udp)$'

# Input Format:
# [
#     '80:8080/tcp',
#     '123:123/udp'
#     '4040/tcp',
# ]
# Result Format:
# [
#     {
#         'cport': '80',
#         'hport': '8080',
#         'proto': 'tcp',
#     },
#     ...
# ]
def conv_ports2dict(data):
    if not all(isinstance(x, str) for x in data):
        raise TypeError('Expected list or str types.')
    if not all(re.match(REGEXP_PORT_ASSIGN, x, flags=re.IGNORECASE) for x in data):
        raise ValueError('Malformed port assignment.')

    delim = ':'
    portlst = []
    for port_data in data:
        hport, cport = None,port_data
        if delim in cport:
            hport,cport = cport.split(delim, 1)
            if not hport: hport = None
        cport,proto = cport.split('/', 1)
        portlst.append({ 'hport': hport, 'cport': cport, 'proto': proto })
    return portlst

# endof utils.py


# should be HTTP POST request
@templates.route('/templates/<int:template_id>/refresh')
@login_required
@admin_required
def update(template_id):
    template = Template.query.get_or_404(template_id)
    items = []
    try:
        with urllib.request.urlopen(template.url) as fp:
            for entry in json.load(fp):
                # Optional use classmethod from_dict

                ports = conv_ports2dict(entry.get('ports', []))

                template_content = TemplateContent(
                    type=int(entry['type']),
                    title=entry['title'],
                    platform=entry['platform'],
                    description=entry.get('description', ''),
                    name=entry.get('name', entry['title'].lower()),
                    logo=entry.get('logo', ''),
                    image=entry.get('image', ''),
                    notes=entry.get('note', ''),
                    categories=entry.get('categories', ''), # default: '' or []
                    restart_policy=entry.get('restart_policy'),
                    ports=ports,
                    volumes=entry.get('volumes'),
                    env=entry.get('env'),
                )
                items.append(template_content)
    except Exception as exc:
        # connection problems or incorrect JSON data
        flash('Template update failed')
    else:
        db.session.delete(template)
        db.session.commit()

        make_transient(template)
        template.id = None
        template.updated_at = datetime.utcnow()
        template.items = items

        try:
            db.session.add(template)
            db.session.commit()
            print("Template \"" + template.name + "\" updated successfully.")
        except Exception as exc:
            db.session.rollback()
            raise

    return redirect(url_for('templates.view_templates'))


# Below section is not in use yet


@templates.route('/new-compose', methods=['GET', 'POST'])  # Set URL
@login_required
@admin_required  # Require admin permissions
def new_compose():
    """Add a new app template."""
    form = ComposeForm(request.form)  # Set the form for this page

    if form.validate_on_submit():
        # Check the file type and depending on the file, download it and add it to the db.
        template_name = form.template_name.data
        template_url = form.template_url.data  # Set var for template_url
        description = form.description
        flash("added template: " + template_url)
        template_path = urlparse(template_url).path  # Get the file path
        ext = os.path.splitext(template_path)[1]  # Get the file extension
        flash("Extension = " + ext)

        if ext in ('.yml', '.yaml'):
            flash('var = .yaml')
            template_path = wget.download(
                template_url, out='app/storage/templates/compose')
            flash(template_path)
        # Add the template to the database with basic info
        template = Compose(
            name=template_name,
            url=template_url,
            path=template_path,
            description=description
        )
        try:

app/templates/app_templates/app_info.html
{% extends 'layouts/base.html' %}
{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
                <div class="ui compact basic buttons">
                    <a class="ui basic compact button" href="{{ url_for('templates.template_content', template_id=template.id) }}">
                        <i class="caret left icon"></i>
                        Back to all templates
                    </a>
                </div>
            <div class="ui compact basic right floated buttons">
                <a class="ui basic compact right floated button" href="{{ url_for('apps.deploy_app', app_id=app.id,) }}">
                    <i class="rocket icon"></i>
                    Deploy Application
                </a>
            </div>
        </div>
        <div class="twelve wide column">
        <img class="ui bordered circular image" src={{ app.logo|tojson }} style="width:200px;height:200px;object-fit:contain;object-position:center;">
            <h2 class="ui header">
                {{ app.name }}
                <div class="sub header">View and deploy {{ app.name }}.</div>
            </h2>
            </p> {{ app.description|safe }} </p>
            {% if app.notes %}
            <div class="ui message">
                <div class="header">
                    Note:
                </div>
                <p>
                    {{ app.notes|safe }}
                </p>
            </div>
            {% endif %}
        </div>
    <div class="twelve wide column">
            <div class=" ui horizontal section divider "> General </div>
                <table class="ui green definition table">
                    <tr><td>Title</td><td>{{ app.title }}</td></tr>
                    <tr><td>Name</td><td>{{ app.name }}</td></tr>
                    <tr><td>Image</td><td>{{ app.image }}</td></tr>
                    <tr><td>Platform</td><td>{{ app.platform }}</td></tr>
                    <tr><td>Categories</td><td>{% for category in app.categories %} {{ category }} {%endfor%}</td></tr>
                    <tr><td>Template Name</td><td>{{ template.name }}</td></tr>
                    <tr><td>Template URL</td><td>{{ template.url }}</td></tr>
                </table>
    {% if app.volumes %}
        <div class="six wide column">
            <div class=" ui horizontal section divider "> Volumes </div>
            <table class="ui selectable blue table">
                <thead>
                    <tr>
                        <th>Container Path</th>
                        <th>Host Path</th>
                    </tr>
                </thead>
                <tbody>
                    {% for mount in app.volumes %}
                        <tr>
                            <td>{{ mount.get('bind') }}</td>
                            <td>{{ mount.get('container') }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
    {% if app.ports %}
        <div class="six wide column">
            <div class="ui horizontal section divider "> Networking </div>
            <table class="ui selectable orange table">
                <thead>
                    <tr>
                        <th>Host Port</th>
                        <th>Container Port</th>
                        <th>Protocol</th>
                    </tr>
                </thead>
                <tbody>
                {% for port in app.ports %}
                    <tr>
                        <td>{{port.get('hport')}}</td>
                        <td>{{port.get('cport')}}</td>
                        <td>{{port.get('proto')}}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
    {% if app.env %}
        <div class="sixteen wide column">
            <div class=" ui horizontal section divider "> Environment Variables </div>
            <table class="ui selectable yellow table">
                <thead>
                    <tr>
                        <th>Variable Name</th>
                        <th class="right aligned">Variable Value</th>
                    </tr>
                </thead>
                <tbody>
                    {% for env in app.env %}
                    <tr>
                        <td>{{ env.get('name') }}</td>
                        <td class="right aligned">{{ env.get('default') }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </div>
        </div>
    {% endif %}

{% endblock %}

app/templates/app_templates/index.html
{% extends 'layouts/base.html' %}

{% macro dashboard_option(title, endpoint, description=None, icon=None) %}
    <a class="column" href="{{ url_for(endpoint) }}">
        <div class="ui padded segment">
        {% if title == 'Add New Compose' %}
            <h3 class="ui disabled header"
        {% else %}
            <h3 class="ui header">
        {% endif %}
                {% if icon is not none %}
                    <i class="{{ icon }}"></i>
                {% endif %}
                <div class="content">
                    {{ title }}
                    {% if description is not none %}
                        <div class="sub header">
                            {{ description }}
                        </div>
                    {% endif %}
                </div>
            </h3>
        </div>
    </a>
{% endmacro %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <!-- Flash messages if they exist -->
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            <ul>
                {% for message in messages %}
                <li style="color: tomato;">{{ message }}</li>
                {% endfor %}
            </ul>
            <hr>
            {% endif %}
            {% endwith %}

            <h2 class="ui header">
                Template Dashboard
            </h2>
            <div class="ui two column stackable grid"> {# Code for deploying the main apps dashboard #}
                {{ dashboard_option('View Templates', 'templates.view_templates',
                                    description='View and manage templates', icon='list layout icon') }}
                {{ dashboard_option('Add New Template', 'templates.new_template',
                                    description='Add a new template manifest', icon='add icon') }}
                {{ dashboard_option('Add New Compose', 'templates.new_compose',
                                    description='Add a new docker-compose template manifest', icon='add icon') }}
            </div>
        </div>
    </div>
{% endblock %}

app/templates/app_templates/manage_templates.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}

{% set deletion_endpoint = 'templates.delete_template_request' %}

{% set endpoints = [
    ('templates.template_info', 'Template Information'),
    ('templates.template_content', 'Template Content'),
    (deletion_endpoint, 'Delete Template')
] %}

{% macro navigation(items) %}
    <div class="ui vertical fluid secondary menu">
        {% for route, name in items %} {# Shows data associated with template clicked on in view_templates.html #}
            {% set href = url_for(route, template_id=template.id) %}
            <a class="item {% if request.endpoint == route %}active{% endif %}" href="{{ href }}">
                {{ name }}
            </a>
        {% endfor %}
    </div>
{% endmacro %}
{# Show data for template #}
{% macro template_info(template) %}
    <table class="ui compact very basic table">
        <tr><td>Template Name</td><td>{{ template.name }}</td></tr>
        <tr><td>Template URL</td><td>{{ template.url }}</td></tr>
        <tr><td>Template Updated</td><td>{{ moment(template.updated_at).fromNow() }}</td></tr>
        <tr><td>Template Created</td><td>{{ moment(template.created_at).fromNow() }}</td></tr>
    </table>
{% endmacro %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <div class="ui compact basic buttons">
                <a class="ui basic compact button" href="{{ url_for('templates.view_templates') }}">
                    <i class="caret left icon"></i>
                    Back to all templates
                </a>
            </div>
            <h2 class="ui header">
                {{ template.name }}
                <div class="sub header">View and manage {{ template.name }}.</div>
            </h2>
        </div>
        <div class="stretched divided very relaxed row">
            <div class="four wide column">
                {{ navigation(endpoints) }}
            </div>
            <div class="ten wide column"> {# Show deletion tab if it's clicked on #}
                {% if request.endpoint == deletion_endpoint %}
                    <h3 class="ui red block header">
                        <i class="warning circle icon"></i>
                        <div class="content">
                            This action is permanent
                            <div class="sub header">
                                Deleting a template is not a reversible change. Any apps associated
                                with this template will be removed, and cannot be recovered.
                            </div>
                        </div>
                    </h3>

                    <div class="ui form">
                        <div class="inline field">
                            <div class="ui deletion checkbox">
                                <input type="checkbox" tabindex="0" class="hidden">
                                <label>I understand that this action cannot be undone.</label>
                            </div>
                        </div>
                        <a class="ui disabled negative deletion button">
                            Delete this template
                        </a>
                    </div>
                    </div>
                {% elif form %} {# Not currently used #}
                    {{ f.render_form(form) }}
                {% elif apps %} {# Show application list #}
                    <div class=" ui horizontal section divider "> Apps </div>
                        <div class="ui three column middle aligned centered grid">
                            <div class="ui three stackable raised blue link cards">
                            {%- for app in apps %}
                            {# <div class="column"> #}
                                <div class="card" onclick="window.location.href = '{{ url_for('templates.template_content_app', app_id=app.id, template_id=template.id) }}';">
                                    <div class="ui centered image">
                                    <img src={{ app.logo|tojson }} style="width:200px;height:200px;object-fit:contain;object-position:center;">
                                    </div>
                                    <div class="content">
                                    <div class="header">{{ app.title }}</div>
                                    <div class="meta">
                                        {% for c in app.categories %}
                                        <a> {{ c }} </a>
                                        {% endfor %}
                                    </div>
                                    <div class="description">
                                        {% if app.description %}
                                            {{ app.description| truncate(160, False) }}
                                        {% endif %}
                                    </div>
                                    </div>
                                </div>
                            {# </div> #}
                            {%- endfor %}
                        </div>
                    </div>
                {% else %} {# Show template info listed above #}
                    {{ template_info(template) }}
                {% endif %}
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $('.deletion.checkbox').checkbox({
            onChecked: function() {
                $('.deletion.button').removeClass('disabled') {# Template Deletion Function #}
                        .attr('href', '{{ url_for('templates.delete_template', template_id=template.id) }}');
            },
            onUnchecked: function() {
                $('.deletion.button').addClass('disabled').removeAttr('href');
            }
        });
    </script>
{% endblock %}

app/templates/app_templates/new_compose.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% import 'macros/check_password.html' as check %}

{% block scripts %}
{% endblock %}
{# Not in use yet #}
{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <div class="ui compact basic buttons">
                <a class="ui basic compact button" href="{{ url_for('templates.index') }}">
                    <i class="caret left icon"></i>
                    Back to dashboard
                </a>
            </div>
            <h2 class="ui header">
                New Compose Template
                <div class="sub header">Add a new app template</div>
                {% set flashes = {
                    'error':   get_flashed_messages(category_filter=['form-error']),
                    'warning': get_flashed_messages(category_filter=['form-check-email']),
                    'info':    get_flashed_messages(category_filter=['form-info']),
                    'success': get_flashed_messages(category_filter=['form-success'])
                } %}
    
                {{ f.begin_form(form, flashes) }}

                    {{ f.render_form_field(form.template_name)}}
                    {{ f.render_form_field(form.template_url) }}
                    {{ f.render_form_field(form.description)}}
                    {{ f.render_form_field(form.submit) }}
    
                {{ f.end_form() }}
            </h2>
        </div>
    </div>
{% endblock %}

app/templates/app_templates/new_template.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% import 'macros/check_password.html' as check %}

{% block scripts %}
{% endblock %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <div class="ui compact basic buttons">
                <a class="ui basic compact button" href="{{ url_for('templates.index') }}">
                    <i class="caret left icon"></i>
                    Back to dashboard
                </a>
            </div>
            <h2 class="ui header">
                New App Template
                <div class="sub header">Add a new app template</div>
                {% set flashes = {
                    'error':   get_flashed_messages(category_filter=['form-error']),
                    'warning': get_flashed_messages(category_filter=['form-check-email']),
                    'info':    get_flashed_messages(category_filter=['form-info']),
                    'success': get_flashed_messages(category_filter=['form-success'])
                } %}
                    {# Form for adding a new template #}
                {{ f.begin_form(form, flashes) }}

                    {{ f.render_form_field(form.template_name)}}
                    {{ f.render_form_field(form.template_url) }}
                    {{ f.render_form_field(form.submit) }}
    
                {{ f.end_form() }}
            </h2>
        </div>
    </div>
{% endblock %}

app/templates/app_templates/view_templates.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="ui stackable grid container">
        <div class="fourteen wide tablet twelve wide computer centered column">
            <a class="ui basic compact button" href="{{ url_for('templates.index') }}">
                <i class="caret left icon"></i>
                Back to dashboard
            </a>
            <h2 class="ui header">
                Saved Templates
                <div class="sub header">
                    View and manage currently saved templates.
                </div>
            </h2>

            <div class="ui menu">
                <div id="select-role" class="ui dropdown item">
                    <div class="text">
                        All template types
                    </div>
                    <i class="dropdown icon"></i>
                    <div class="menu">
                        <div class="item" data-value="">All account types</div>
                        {% for r in roles %}
                            <div class="item" data-value="{{ r.name }}">{{ r.name }}s</div>
                        {% endfor %}
                    </div>
                </div>
                <div class="ui right search item">
                    <div class="ui transparent icon input">
                        <input id="search-users" type="text" placeholder="Search templates…">
                        <i class="search icon"></i>
                    </div>
                </div>
            </div>

            {# Use overflow-x: scroll so that mobile views don't freak out
             # when the table is too wide #}
            <div style="overflow-x: auto;">
                <table class="ui searchable sortable unstackable selectable celled blue table">
                    <thead>
                        <tr>
                            <th class="sorted ascending">Template Name</th>
                            <th>Template URL</th>
                            <th colspan="2">Updated</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for t in template | sort(attribute='name') %} {# Show table of templates #}
                        <tr onclick="window.location.href = '{{ url_for('templates.template_info', template_id=t.id) }}';">
                            <td>{{ t.name }}</td>
                            <td>{{ t.url }}</td>
                            <td>{{ moment(t.updated_at).fromNow() }}</td>
                            <td>
                                <a href = '{{ url_for('templates.update', template_id=t.id) }}'>
                                    <button class="ui fluid blue labeled icon button">
                                        <i class="sync alternate icon"></i>
                                        Update
                                    </button>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#search-users').keyup(function () {
                var searchText = $(this).val();
                if (searchText.length > 0) {
                    $('tbody td:icontains(' + searchText + ')').addClass('positive');
                    $('td.positive').not(':icontains(' + searchText + ')').removeClass('positive');
                    $('tbody td').not(':icontains(' + searchText + ')').closest('tr').addClass('hidden').hide();
                    $('tr.hidden:icontains(' + searchText + ')').removeClass('hidden').show();
                } else {
                    $('td.positive').removeClass('positive');
                    $('tr.hidden').removeClass('hidden').show();
                }
            });

            $('#select-role').dropdown({
                onChange: function (value, text, $selectedItem) {
                    $('td.user.role:contains(' + value + ')').closest('tr').removeClass('hidden').show();
                    $('td.user.role').not(':contains(' + value + ')').closest('tr').addClass('hidden').hide();
                }
            });
        });
    </script>
{% endblock %}